import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRiskColumns1768932724209 implements MigrationInterface {
    name = 'AddRiskColumns1768932724209'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "chat_participant" DROP CONSTRAINT "FK_chat_participant_conversation"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_chat_message_conversation"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_e87f74fc2f41b80635e686ec4fa"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP CONSTRAINT "FK_38bff4c45d32b0a3b8e9e83e6f2"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP CONSTRAINT "FK_b11c9c710cf1a552d5de156329c"`);
        await queryRunner.query(`ALTER TABLE "user_badge" DROP CONSTRAINT "FK_user_badge_userId"`);
        await queryRunner.query(`ALTER TABLE "user_badge" DROP CONSTRAINT "FK_user_badge_badgeId"`);
        await queryRunner.query(`ALTER TABLE "form_field" DROP CONSTRAINT "FK_form_field_form"`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP CONSTRAINT "FK_form_submission_form"`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" DROP CONSTRAINT "FK_form_submission_chat_submission"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" DROP CONSTRAINT "FK_nr1_risk_records_criterios"`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" DROP CONSTRAINT "FK_nr1_action_plans_risk"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b11c9c710cf1a552d5de156329"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38bff4c45d32b0a3b8e9e83e6f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NEWS_ACK_UNIQUE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NEWS_ACK_NEWS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NEWS_ACK_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NEWS_ACK_COMPANY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_badge_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_template"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_nr1_risk_criteria_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c87ae7b676bd8fd6fa1357026a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c872b3ff934cb40e9a76faedea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_nr1_risk_records_context"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_nr1_risk_records_company_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_nr1_action_plans_status_priority"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_nr1_action_plans_responsavel_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_nr1_action_plans_risk_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_nr1_trainings_company"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP COLUMN "employeeId"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP COLUMN "managerId"`);
        await queryRunner.query(`ALTER TABLE "journey_steps" DROP COLUMN "linkedFormId"`);
        await queryRunner.query(`ALTER TABLE "journey_steps" DROP COLUMN "linkedPollId"`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" DROP COLUMN "readAt"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "performance_cycles" ADD "templateId" character varying`);
        await queryRunner.query(`ALTER TABLE "performance_cycles" ADD "includeCalibration" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD "companyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD "organizerUserId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD "participantUserId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD "scheduledDate" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD "status" character varying NOT NULL DEFAULT 'SCHEDULED'`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD "actionItems" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP CONSTRAINT "PK_form_badge_state"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD CONSTRAINT "PK_form_badge_state" PRIMARY KEY ("companyId", "formId", "cmsUserId", "id")`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "company_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ADD "probabilidade" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ADD "severidade" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "conditions" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "isChatEnabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "adminIds" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94b3b7ca35b96e0514d22dc55f"`);
        await queryRunner.query(`ALTER TYPE "public"."user_xp_history_actiontype_enum" RENAME TO "user_xp_history_actiontype_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."user_xp_history_actiontype_enum" AS ENUM('JOURNEY_STEP', 'JOURNEY_COMPLETION', 'NEWS_READ', 'NEWS_REACTION', 'NEWS_COMMENT', 'NEWS_SHARE', 'SURVEY_COMPLETION', 'SOCIAL_POST', 'SOCIAL_COMMENT', 'SOCIAL_REACTION', 'SOCIAL_SHARE', 'MANUAL_AWARD', 'PROFILE_UPDATE', 'VIDEO_WATCH', 'FORM_SUBMISSION', 'AGREEMENT_ACCEPT')`);
        await queryRunner.query(`ALTER TABLE "user_xp_history" ALTER COLUMN "actionType" TYPE "public"."user_xp_history_actiontype_enum" USING "actionType"::"text"::"public"."user_xp_history_actiontype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_xp_history_actiontype_enum_old"`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "distributionChannels" SET DEFAULT ARRAY['app']`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD "companyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD "role" character varying`);
        await queryRunner.query(`ALTER TABLE "user_entity" ALTER COLUMN "groups" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TYPE "public"."channel_type_enum" RENAME TO "channel_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."channel_type_enum" AS ENUM('articles', 'media', 'updates', 'social')`);
        await queryRunner.query(`ALTER TABLE "channel" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "channel" ALTER COLUMN "type" TYPE "public"."channel_type_enum" USING "type"::"text"::"public"."channel_type_enum"`);
        await queryRunner.query(`ALTER TABLE "channel" ALTER COLUMN "type" SET DEFAULT 'articles'`);
        await queryRunner.query(`DROP TYPE "public"."channel_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "platform"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "platform" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "token" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "deviceId"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "deviceId" text`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "userAgent" text`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "locale"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "locale" text`);
        await queryRunner.query(`ALTER TABLE "user_device" ALTER COLUMN "enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news_entity" DROP COLUMN "channelId"`);
        await queryRunner.query(`ALTER TABLE "news_entity" ADD "channelId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_entity" ALTER COLUMN "hashtags" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "news_entity" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "news_entity" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "survey" ALTER COLUMN "spaceIds" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TABLE "survey" ALTER COLUMN "groupIds" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TABLE "chat_conversation" DROP CONSTRAINT "UQ_linkedGroupId"`);
        await queryRunner.query(`ALTER TABLE "chat_conversation" DROP COLUMN "linkedGroupId"`);
        await queryRunner.query(`ALTER TABLE "chat_conversation" ADD "linkedGroupId" character varying`);
        await queryRunner.query(`ALTER TABLE "chat_conversation" ADD CONSTRAINT "UQ_4ff4bcfb48b7db736e509a0b5a8" UNIQUE ("linkedGroupId")`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ALTER COLUMN "talkingPoints" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "createdBy" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "visibility"`);
        await queryRunner.query(`CREATE TYPE "public"."form_visibility_enum" AS ENUM('public', 'private', 'specific_groups', 'journey_only')`);
        await queryRunner.query(`ALTER TABLE "form" ADD "visibility" "public"."form_visibility_enum" NOT NULL DEFAULT 'public'`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "status" text NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "remindersConfig" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "notificationsConfig" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "defaultLocale"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "defaultLocale" text DEFAULT 'pt-BR'`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "acl" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "acl" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_field" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form_field" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_field" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "form_field" ADD "type" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_field" ALTER COLUMN "label" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "form_field" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form_field" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_submission" ALTER COLUMN "submittedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "externalEmail"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "externalEmail" text`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "status" text NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "chatStatus"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "chatStatus" text NOT NULL DEFAULT 'open'`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" DROP COLUMN "actor"`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" ADD "actor" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP CONSTRAINT "PK_form_badge_state"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD CONSTRAINT "PK_form_badge_state" PRIMARY KEY ("formId", "cmsUserId", "id")`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP CONSTRAINT "PK_form_badge_state"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD CONSTRAINT "PK_form_badge_state" PRIMARY KEY ("formId", "id")`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP COLUMN "cmsUserId"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD "cmsUserId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP CONSTRAINT "PK_form_badge_state"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD CONSTRAINT "PK_6f44bf28c423e1cc6b36d43574b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ALTER COLUMN "newCount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ALTER COLUMN "errorCount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "integration_runs" DROP CONSTRAINT "FK_1ad2e3de433c59725ba920834fb"`);
        await queryRunner.query(`ALTER TYPE "public"."integration_runs_type_enum" RENAME TO "integration_runs_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."integration_runs_type_enum" AS ENUM('full', 'delta')`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "type" TYPE "public"."integration_runs_type_enum" USING "type"::"text"::"public"."integration_runs_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."integration_runs_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."integration_runs_status_enum" RENAME TO "integration_runs_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."integration_runs_status_enum" AS ENUM('running', 'success', 'failed', 'partial')`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "status" TYPE "public"."integration_runs_status_enum" USING "status"::"text"::"public"."integration_runs_status_enum"`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "status" SET DEFAULT 'running'`);
        await queryRunner.query(`DROP TYPE "public"."integration_runs_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "connection_id" DROP NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10c65e0105f10f0cb44c8dfedd"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_criteria" ALTER COLUMN "version" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_criteria" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b9170a817984af912feb734d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_508f54765fe2a11f2fd52c2008"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_action_priority_enum" RENAME TO "nr1_action_priority_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_action_plans_prioridade_enum" AS ENUM('P0', 'P1', 'P2', 'P3')`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "prioridade" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "prioridade" TYPE "public"."nr1_action_plans_prioridade_enum" USING "prioridade"::"text"::"public"."nr1_action_plans_prioridade_enum"`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "prioridade" SET DEFAULT 'P2'`);
        await queryRunner.query(`DROP TYPE "public"."nr1_action_priority_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_action_status_enum" RENAME TO "nr1_action_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_action_plans_status_enum" AS ENUM('planejado', 'em_execucao', 'concluido', 'atrasado', 'cancelado')`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "status" TYPE "public"."nr1_action_plans_status_enum" USING "status"::"text"::"public"."nr1_action_plans_status_enum"`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "status" SET DEFAULT 'planejado'`);
        await queryRunner.query(`DROP TYPE "public"."nr1_action_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_training_type_enum" RENAME TO "nr1_training_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_trainings_tipo_enum" AS ENUM('inicial', 'periodico', 'eventual')`);
        await queryRunner.query(`ALTER TABLE "nr1_trainings" ALTER COLUMN "tipo" TYPE "public"."nr1_trainings_tipo_enum" USING "tipo"::"text"::"public"."nr1_trainings_tipo_enum"`);
        await queryRunner.query(`DROP TYPE "public"."nr1_training_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_training_modality_enum" RENAME TO "nr1_training_modality_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_trainings_modalidade_enum" AS ENUM('presencial', 'EAD', 'semipresencial')`);
        await queryRunner.query(`ALTER TABLE "nr1_trainings" ALTER COLUMN "modalidade" TYPE "public"."nr1_trainings_modalidade_enum" USING "modalidade"::"text"::"public"."nr1_trainings_modalidade_enum"`);
        await queryRunner.query(`DROP TYPE "public"."nr1_training_modality_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_94b3b7ca35b96e0514d22dc55f" ON "user_xp_history" ("userId", "actionType", "createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8ef8f4acbc766ab04848cf24e4" ON "user_space_entity" ("userId", "spaceId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8fb0718aea360688ad9167301d" ON "user_device" ("companyId", "token") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ffb5ea6423bf5dc5f25011890" ON "user_device" ("companyId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_02110bec06bd0e3aa0cdc3b913" ON "news_acknowledgment" ("newsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_34940e6b1793bafab8eb82af2f" ON "news_acknowledgment" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5087c13c563ccd0d99b823444f" ON "news_acknowledgment" ("companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_84738fa7c8ca41d9bd71793b4b" ON "news_acknowledgment" ("newsId", "userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_be9b63df63d3d091441ae9b003" ON "user_badge" ("userId", "badgeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7c21930b8fd234e8b9242a045" ON "form" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f48a4afcd687d8fcd2ec16a913" ON "form" ("createdBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_69b08cacee786568a0f3ba8b9a" ON "form" ("companyId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_529bedfca3fcc7b792aa6bcabf" ON "form_field" ("companyId", "formId", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b296237f00aff299b14ca6487" ON "form_submission" ("submittedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_df8fce71531e6d42f58b1b5470" ON "form_submission" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad2a3a356aff29012d729d7327" ON "form_submission" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_284fadf3a013e993274ebcc2b2" ON "form_submission" ("chatStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_45724160457c892042542b8783" ON "form_submission" ("companyId", "formId", "submittedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa8d13d7ea4de9a7074901eed8" ON "form_submission_chat" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b2e1c21fcc1c43dd069c0712a" ON "form_submission_chat" ("companyId", "submissionId", "createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8acb7557a706ae82bb56f49c1f" ON "form_badge_state" ("companyId", "cmsUserId", "formId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_10c65e0105f10f0cb44c8dfedd" ON "nr1_risk_criteria" ("company_id", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_c872b3ff934cb40e9a76faedea" ON "nr1_risk_types" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_508f54765fe2a11f2fd52c2008" ON "nr1_action_plans" ("responsavel_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b9170a817984af912feb734d6" ON "nr1_action_plans" ("status", "prioridade") `);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD CONSTRAINT "FK_99aca546a4944e681c1d3e78e6b" FOREIGN KEY ("userId") REFERENCES "user_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD CONSTRAINT "FK_f171fca48b9edbae7d7d3a2282b" FOREIGN KEY ("spaceId") REFERENCES "space"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_entity" ADD CONSTRAINT "FK_f1a11e7e1d4037f94c32180b84c" FOREIGN KEY ("channelId") REFERENCES "channel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participant" ADD CONSTRAINT "FK_889ddea52e3b1dd82d5961c707b" FOREIGN KEY ("conversationId") REFERENCES "chat_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participant" ADD CONSTRAINT "FK_b222da2539ff0a06a8f5493f868" FOREIGN KEY ("userId") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_71d77a16df3f16e830d645f31f6" FOREIGN KEY ("conversationId") REFERENCES "chat_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_a2be22c99b34156574f4e02d0a0" FOREIGN KEY ("senderId") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_e87f74fc2f41b80635e686ec4fa" FOREIGN KEY ("replyToId") REFERENCES "chat_message"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badge" ADD CONSTRAINT "FK_dc6bb11dce7a0a591b5cae0af25" FOREIGN KEY ("userId") REFERENCES "user_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badge" ADD CONSTRAINT "FK_8a49533f303db990198b8c9ddf7" FOREIGN KEY ("badgeId") REFERENCES "gamification_badge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ADD CONSTRAINT "FK_1ad2e3de433c59725ba920834fb" FOREIGN KEY ("connection_id") REFERENCES "integration_connections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "integration_runs" DROP CONSTRAINT "FK_1ad2e3de433c59725ba920834fb"`);
        await queryRunner.query(`ALTER TABLE "user_badge" DROP CONSTRAINT "FK_8a49533f303db990198b8c9ddf7"`);
        await queryRunner.query(`ALTER TABLE "user_badge" DROP CONSTRAINT "FK_dc6bb11dce7a0a591b5cae0af25"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_e87f74fc2f41b80635e686ec4fa"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_a2be22c99b34156574f4e02d0a0"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_71d77a16df3f16e830d645f31f6"`);
        await queryRunner.query(`ALTER TABLE "chat_participant" DROP CONSTRAINT "FK_b222da2539ff0a06a8f5493f868"`);
        await queryRunner.query(`ALTER TABLE "chat_participant" DROP CONSTRAINT "FK_889ddea52e3b1dd82d5961c707b"`);
        await queryRunner.query(`ALTER TABLE "news_entity" DROP CONSTRAINT "FK_f1a11e7e1d4037f94c32180b84c"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP CONSTRAINT "FK_f171fca48b9edbae7d7d3a2282b"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP CONSTRAINT "FK_99aca546a4944e681c1d3e78e6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b9170a817984af912feb734d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_508f54765fe2a11f2fd52c2008"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c872b3ff934cb40e9a76faedea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10c65e0105f10f0cb44c8dfedd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8acb7557a706ae82bb56f49c1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b2e1c21fcc1c43dd069c0712a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa8d13d7ea4de9a7074901eed8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45724160457c892042542b8783"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_284fadf3a013e993274ebcc2b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad2a3a356aff29012d729d7327"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df8fce71531e6d42f58b1b5470"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b296237f00aff299b14ca6487"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_529bedfca3fcc7b792aa6bcabf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69b08cacee786568a0f3ba8b9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f48a4afcd687d8fcd2ec16a913"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7c21930b8fd234e8b9242a045"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be9b63df63d3d091441ae9b003"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84738fa7c8ca41d9bd71793b4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5087c13c563ccd0d99b823444f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34940e6b1793bafab8eb82af2f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02110bec06bd0e3aa0cdc3b913"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ffb5ea6423bf5dc5f25011890"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fb0718aea360688ad9167301d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ef8f4acbc766ab04848cf24e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94b3b7ca35b96e0514d22dc55f"`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_training_modality_enum_old" AS ENUM('presencial', 'EAD', 'semipresencial')`);
        await queryRunner.query(`ALTER TABLE "nr1_trainings" ALTER COLUMN "modalidade" TYPE "public"."nr1_training_modality_enum_old" USING "modalidade"::"text"::"public"."nr1_training_modality_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."nr1_trainings_modalidade_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_training_modality_enum_old" RENAME TO "nr1_training_modality_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_training_type_enum_old" AS ENUM('inicial', 'periodico', 'eventual')`);
        await queryRunner.query(`ALTER TABLE "nr1_trainings" ALTER COLUMN "tipo" TYPE "public"."nr1_training_type_enum_old" USING "tipo"::"text"::"public"."nr1_training_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."nr1_trainings_tipo_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_training_type_enum_old" RENAME TO "nr1_training_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_action_status_enum_old" AS ENUM('planejado', 'em_execucao', 'concluido', 'atrasado', 'cancelado')`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "status" TYPE "public"."nr1_action_status_enum_old" USING "status"::"text"::"public"."nr1_action_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "status" SET DEFAULT 'planejado'`);
        await queryRunner.query(`DROP TYPE "public"."nr1_action_plans_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_action_status_enum_old" RENAME TO "nr1_action_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_action_priority_enum_old" AS ENUM('P0', 'P1', 'P2', 'P3')`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "prioridade" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "prioridade" TYPE "public"."nr1_action_priority_enum_old" USING "prioridade"::"text"::"public"."nr1_action_priority_enum_old"`);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ALTER COLUMN "prioridade" SET DEFAULT 'P2'`);
        await queryRunner.query(`DROP TYPE "public"."nr1_action_plans_prioridade_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_action_priority_enum_old" RENAME TO "nr1_action_priority_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_508f54765fe2a11f2fd52c2008" ON "nr1_action_plans" ("responsavel_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b9170a817984af912feb734d6" ON "nr1_action_plans" ("prioridade", "status") `);
        await queryRunner.query(`ALTER TABLE "nr1_risk_criteria" ALTER COLUMN "version" SET DEFAULT '1.0'`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_criteria" ALTER COLUMN "version" DROP NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_10c65e0105f10f0cb44c8dfedd" ON "nr1_risk_criteria" ("company_id", "version") `);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "connection_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."integration_runs_status_enum_old" AS ENUM('running', 'success', 'partial_success', 'failed')`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "status" TYPE "public"."integration_runs_status_enum_old" USING "status"::"text"::"public"."integration_runs_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "status" SET DEFAULT 'running'`);
        await queryRunner.query(`DROP TYPE "public"."integration_runs_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."integration_runs_status_enum_old" RENAME TO "integration_runs_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."integration_runs_type_enum_old" AS ENUM('full', 'delta', 'test')`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "type" TYPE "public"."integration_runs_type_enum_old" USING "type"::"text"::"public"."integration_runs_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ALTER COLUMN "type" SET DEFAULT 'delta'`);
        await queryRunner.query(`DROP TYPE "public"."integration_runs_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."integration_runs_type_enum_old" RENAME TO "integration_runs_type_enum"`);
        await queryRunner.query(`ALTER TABLE "integration_runs" ADD CONSTRAINT "FK_1ad2e3de433c59725ba920834fb" FOREIGN KEY ("connection_id") REFERENCES "integration_connections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ALTER COLUMN "errorCount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ALTER COLUMN "newCount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP CONSTRAINT "PK_6f44bf28c423e1cc6b36d43574b"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD CONSTRAINT "PK_form_badge_state" PRIMARY KEY ("formId", "id")`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP COLUMN "cmsUserId"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD "cmsUserId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP CONSTRAINT "PK_form_badge_state"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD CONSTRAINT "PK_form_badge_state" PRIMARY KEY ("formId", "cmsUserId", "id")`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD "companyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP CONSTRAINT "PK_form_badge_state"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD CONSTRAINT "PK_form_badge_state" PRIMARY KEY ("companyId", "formId", "cmsUserId", "id")`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" DROP COLUMN "actor"`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" ADD "actor" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" ADD "companyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "chatStatus"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "chatStatus" character varying NOT NULL DEFAULT 'open'`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "externalEmail"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "externalEmail" character varying`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "userId" character varying`);
        await queryRunner.query(`ALTER TABLE "form_submission" ALTER COLUMN "submittedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_submission" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD "companyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_field" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form_field" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_field" ALTER COLUMN "label" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "form_field" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "form_field" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_field" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form_field" ADD "companyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "acl" SET DEFAULT '{"owners": [], "editors": [], "viewers": []}'`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "acl" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "defaultLocale"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "defaultLocale" character varying NOT NULL DEFAULT 'pt-BR'`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "notificationsConfig" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "remindersConfig" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "status" character varying NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "visibility"`);
        await queryRunner.query(`DROP TYPE "public"."form_visibility_enum"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "visibility" text DEFAULT 'public'`);
        await queryRunner.query(`ALTER TABLE "form" ALTER COLUMN "title" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "createdBy" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "form" ADD "companyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ALTER COLUMN "talkingPoints" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "chat_conversation" DROP CONSTRAINT "UQ_4ff4bcfb48b7db736e509a0b5a8"`);
        await queryRunner.query(`ALTER TABLE "chat_conversation" DROP COLUMN "linkedGroupId"`);
        await queryRunner.query(`ALTER TABLE "chat_conversation" ADD "linkedGroupId" uuid`);
        await queryRunner.query(`ALTER TABLE "chat_conversation" ADD CONSTRAINT "UQ_linkedGroupId" UNIQUE ("linkedGroupId")`);
        await queryRunner.query(`ALTER TABLE "survey" ALTER COLUMN "groupIds" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "survey" ALTER COLUMN "spaceIds" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "news_entity" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "news_entity" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "news_entity" ALTER COLUMN "hashtags" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_entity" DROP COLUMN "channelId"`);
        await queryRunner.query(`ALTER TABLE "news_entity" ADD "channelId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_device" ALTER COLUMN "enabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "locale"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "locale" character varying`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "userAgent" character varying`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "deviceId"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "deviceId" character varying`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "token" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "platform"`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "platform" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."channel_type_enum_old" AS ENUM('articles', 'media', 'updates')`);
        await queryRunner.query(`ALTER TABLE "channel" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "channel" ALTER COLUMN "type" TYPE "public"."channel_type_enum_old" USING "type"::"text"::"public"."channel_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "channel" ALTER COLUMN "type" SET DEFAULT 'articles'`);
        await queryRunner.query(`DROP TYPE "public"."channel_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."channel_type_enum_old" RENAME TO "channel_type_enum"`);
        await queryRunner.query(`ALTER TABLE "user_entity" ALTER COLUMN "groups" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD "role" text DEFAULT 'member'`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "distributionChannels" SET DEFAULT ARRAY['app'`);
        await queryRunner.query(`CREATE TYPE "public"."user_xp_history_actiontype_enum_old" AS ENUM('JOURNEY_STEP', 'JOURNEY_COMPLETION', 'NEWS_READ', 'SURVEY_COMPLETION', 'SOCIAL_POST', 'SOCIAL_COMMENT', 'SOCIAL_REACTION', 'MANUAL_AWARD', 'PROFILE_UPDATE', 'VIDEO_WATCH', 'FORM_SUBMISSION', 'AGREEMENT_ACCEPT')`);
        await queryRunner.query(`ALTER TABLE "user_xp_history" ALTER COLUMN "actionType" TYPE "public"."user_xp_history_actiontype_enum_old" USING "actionType"::"text"::"public"."user_xp_history_actiontype_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."user_xp_history_actiontype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_xp_history_actiontype_enum_old" RENAME TO "user_xp_history_actiontype_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_94b3b7ca35b96e0514d22dc55f" ON "user_xp_history" ("userId", "actionType", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "adminIds" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "isChatEnabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "conditions" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" DROP COLUMN "severidade"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" DROP COLUMN "probabilidade"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "company_id"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP CONSTRAINT "PK_form_badge_state"`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" ADD CONSTRAINT "PK_form_badge_state" PRIMARY KEY ("companyId", "formId", "cmsUserId")`);
        await queryRunner.query(`ALTER TABLE "form_badge_state" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP COLUMN "actionItems"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP COLUMN "scheduledDate"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP COLUMN "participantUserId"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP COLUMN "organizerUserId"`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "performance_cycles" DROP COLUMN "includeCalibration"`);
        await queryRunner.query(`ALTER TABLE "performance_cycles" DROP COLUMN "templateId"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "companyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" ADD "readAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "journey_steps" ADD "linkedPollId" character varying`);
        await queryRunner.query(`ALTER TABLE "journey_steps" ADD "linkedFormId" character varying`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD "managerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD "date" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD "employeeId" uuid NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_nr1_trainings_company" ON "nr1_trainings" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_nr1_action_plans_risk_id" ON "nr1_action_plans" ("risk_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_nr1_action_plans_responsavel_status" ON "nr1_action_plans" ("responsavel_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_nr1_action_plans_status_priority" ON "nr1_action_plans" ("prioridade", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_nr1_risk_records_company_status" ON "nr1_risk_records" ("company_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_nr1_risk_records_context" ON "nr1_risk_records" ("company_id", "space_id", "channel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c872b3ff934cb40e9a76faedea" ON "nr1_risk_types" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c87ae7b676bd8fd6fa1357026a" ON "nr1_risk_types" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_nr1_risk_criteria_company_id" ON "nr1_risk_criteria" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_template" ON "form" ("companyId", "template") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_badge_unique" ON "user_badge" ("userId", "badgeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_NEWS_ACK_COMPANY" ON "news_acknowledgment" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_NEWS_ACK_USER" ON "news_acknowledgment" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_NEWS_ACK_NEWS" ON "news_acknowledgment" ("newsId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_NEWS_ACK_UNIQUE" ON "news_acknowledgment" ("newsId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_38bff4c45d32b0a3b8e9e83e6f" ON "one_on_ones" ("managerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b11c9c710cf1a552d5de156329" ON "one_on_ones" ("employeeId") `);
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" ADD CONSTRAINT "FK_nr1_action_plans_risk" FOREIGN KEY ("risk_id") REFERENCES "nr1_risk_records"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ADD CONSTRAINT "FK_nr1_risk_records_criterios" FOREIGN KEY ("criterios_id") REFERENCES "nr1_risk_criteria"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "form_submission_chat" ADD CONSTRAINT "FK_form_submission_chat_submission" FOREIGN KEY ("submissionId") REFERENCES "form_submission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submission" ADD CONSTRAINT "FK_form_submission_form" FOREIGN KEY ("formId") REFERENCES "form"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_field" ADD CONSTRAINT "FK_form_field_form" FOREIGN KEY ("formId") REFERENCES "form"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badge" ADD CONSTRAINT "FK_user_badge_badgeId" FOREIGN KEY ("badgeId") REFERENCES "gamification_badge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badge" ADD CONSTRAINT "FK_user_badge_userId" FOREIGN KEY ("userId") REFERENCES "user_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD CONSTRAINT "FK_b11c9c710cf1a552d5de156329c" FOREIGN KEY ("employeeId") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "one_on_ones" ADD CONSTRAINT "FK_38bff4c45d32b0a3b8e9e83e6f2" FOREIGN KEY ("managerId") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_e87f74fc2f41b80635e686ec4fa" FOREIGN KEY ("replyToId") REFERENCES "chat_message"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_chat_message_conversation" FOREIGN KEY ("conversationId") REFERENCES "chat_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participant" ADD CONSTRAINT "FK_chat_participant_conversation" FOREIGN KEY ("conversationId") REFERENCES "chat_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
