version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: iuppy_user
      POSTGRES_PASSWORD: Iuppy2025
      POSTGRES_DB: iuppy_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://iuppy_user:Iuppy2025@postgres:5432/iuppy_dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - ../shared:/usr/src/shared
      - /usr/src/app/node_modules

volumes:
  postgres_data:
