import { MigrationInterface, QueryRunner } from "typeorm";

export class AddIsNr1ToJourneyAndForm1768836309437 implements MigrationInterface {
    name = 'AddIsNr1ToJourneyAndForm1768836309437'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DO $$ BEGIN IF EXISTS(SELECT * FROM information_schema.columns WHERE table_name='nr1_risk_criteria' AND column_name='versao') THEN IF EXISTS(SELECT * FROM information_schema.columns WHERE table_name='nr1_risk_criteria' AND column_name='version') THEN ALTER TABLE "nr1_risk_criteria" DROP COLUMN "versao"; ELSE ALTER TABLE "nr1_risk_criteria" RENAME COLUMN "versao" TO "version"; END IF; END IF; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."nr1_action_plans_prioridade_enum" AS ENUM('P0', 'P1', 'P2', 'P3'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."nr1_action_plans_status_enum" AS ENUM('planejado', 'em_execucao', 'concluido', 'atrasado', 'cancelado'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "nr1_action_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "risk_id" uuid NOT NULL, "medida_prevencao" text NOT NULL, "prioridade" "public"."nr1_action_plans_prioridade_enum" NOT NULL DEFAULT 'P2', "responsavel_id" uuid, "inicio_previsto" date, "fim_previsto" date, "forma_acompanhamento" text, "kpi" jsonb, "status" "public"."nr1_action_plans_status_enum" NOT NULL DEFAULT 'planejado', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2d35586ceb2e3088cf0d658c84d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_237d44799ea81953bbf8077406" ON "nr1_action_plans" ("responsavel_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_508f54765fe2a11f2fd52c2008" ON "nr1_action_plans" ("responsavel_id", "status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_8b9170a817984af912feb734d6" ON "nr1_action_plans" ("status", "prioridade") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4c6b4d9e169fbf70fe0e770a7a" ON "nr1_action_plans" ("risk_id") `);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."nr1_trainings_tipo_enum" AS ENUM('inicial', 'periodico', 'eventual'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."nr1_trainings_modalidade_enum" AS ENUM('presencial', 'EAD', 'semipresencial'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "nr1_trainings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "titulo" text NOT NULL, "tipo" "public"."nr1_trainings_tipo_enum" NOT NULL, "modalidade" "public"."nr1_trainings_modalidade_enum" NOT NULL, "carga_horaria" numeric(5,1) NOT NULL, "projeto_pedagogico_url" text, "conteudos" jsonb NOT NULL, "requisitos_anexo_ii" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_de4b81b7d8e682c3f765b254c9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_a9d16cbcb2f203b11923ef8dc6" ON "nr1_trainings" ("company_id") `);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP CONSTRAINT IF EXISTS "PK_33acff6f9897bd850d19963eae3"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP COLUMN IF EXISTS "id"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP COLUMN IF EXISTS "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD IF NOT EXISTS "role" character varying`);
        await queryRunner.query(`ALTER TABLE "news_entity" ADD IF NOT EXISTS "isNr1" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "journey_steps" ADD IF NOT EXISTS "quizConfig" jsonb`);
        await queryRunner.query(`ALTER TABLE "journeys" ADD IF NOT EXISTS "isNr1" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "gamification_badge" ADD IF NOT EXISTS "isNr1" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "form" ADD IF NOT EXISTS "isNr1" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "user_space_entity" ADD CONSTRAINT "PK_8ef8f4acbc766ab04848cf24e43" PRIMARY KEY ("userId", "spaceId"); EXCEPTION WHEN duplicate_object THEN null; WHEN duplicate_table THEN null; WHEN invalid_table_definition THEN null; END $$;`);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "conditions" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "adminIds" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "distributionChannels" SET DEFAULT ARRAY['app']`);
        await queryRunner.query(`ALTER TABLE "user_entity" ALTER COLUMN "groups" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TABLE "survey" ALTER COLUMN "spaceIds" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TABLE "survey" ALTER COLUMN "groupIds" SET DEFAULT ARRAY[]::text[]`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN IF EXISTS "name"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD IF NOT EXISTS "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN IF EXISTS "description"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD IF NOT EXISTS "description" character varying`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN IF EXISTS "color"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD IF NOT EXISTS "color" character varying`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN IF EXISTS "icon"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD IF NOT EXISTS "icon" character varying`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN IF EXISTS "created_at"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD IF NOT EXISTS "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN IF EXISTS "updated_at"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD IF NOT EXISTS "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_risk_level_enum" RENAME TO "nr1_risk_level_enum_old"`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."nr1_risk_records_classificacao_risco_enum" AS ENUM('b', 'm', 'a', 'ma'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ALTER COLUMN "classificacao_risco" TYPE "public"."nr1_risk_records_classificacao_risco_enum" USING "classificacao_risco"::"text"::"public"."nr1_risk_records_classificacao_risco_enum"`);
        await queryRunner.query(`DROP TYPE IF EXISTS "public"."nr1_risk_level_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_risk_status_enum" RENAME TO "nr1_risk_status_enum_old"`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."nr1_risk_records_status_enum" AS ENUM('ativo', 'inativo'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ALTER COLUMN "status" TYPE "public"."nr1_risk_records_status_enum" USING "status"::"text"::"public"."nr1_risk_records_status_enum"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ALTER COLUMN "status" SET DEFAULT 'ativo'`);
        await queryRunner.query(`DROP TYPE IF EXISTS "public"."nr1_risk_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "environment" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "configured" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "connectionTested" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_71b32a770a5be1248e5ffbc113" ON "nr1_risk_criteria" ("company_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_10c65e0105f10f0cb44c8dfedd" ON "nr1_risk_criteria" ("company_id", "version") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_c872b3ff934cb40e9a76faedea" ON "nr1_risk_types" ("companyId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ae1964f4d37ebc00106e3e5eb1" ON "nr1_risk_records" ("company_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_64836d40b00731d07445abf071" ON "nr1_risk_records" ("space_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_7306be8851c1b15e23e059c434" ON "nr1_risk_records" ("channel_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ec9d1b867b8a964b7d4e2a3d94" ON "nr1_risk_records" ("company_id", "space_id", "channel_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_60280f8e57fec41bd5e32326fa" ON "nr1_risk_records" ("company_id", "status") `);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "nr1_risk_records" ADD CONSTRAINT "FK_491cdedcb462e93b6b0f1b77d3d" FOREIGN KEY ("criterios_id") REFERENCES "nr1_risk_criteria"("id") ON DELETE SET NULL ON UPDATE CASCADE; EXCEPTION WHEN duplicate_object THEN null; WHEN duplicate_table THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "nr1_risk_records" ADD CONSTRAINT "FK_c656ae9a7e8eacbb63be152f86b" FOREIGN KEY ("risk_type_id") REFERENCES "nr1_risk_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; WHEN duplicate_table THEN null; END $$;`);
        await queryRunner.query(`DO $$ BEGIN ALTER TABLE "nr1_action_plans" ADD CONSTRAINT "FK_4c6b4d9e169fbf70fe0e770a7aa" FOREIGN KEY ("risk_id") REFERENCES "nr1_risk_records"("id") ON DELETE CASCADE ON UPDATE NO ACTION; EXCEPTION WHEN duplicate_object THEN null; WHEN duplicate_table THEN null; END $$;`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "nr1_action_plans" DROP CONSTRAINT "FK_4c6b4d9e169fbf70fe0e770a7aa"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" DROP CONSTRAINT "FK_c656ae9a7e8eacbb63be152f86b"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" DROP CONSTRAINT "FK_491cdedcb462e93b6b0f1b77d3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60280f8e57fec41bd5e32326fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec9d1b867b8a964b7d4e2a3d94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7306be8851c1b15e23e059c434"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64836d40b00731d07445abf071"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae1964f4d37ebc00106e3e5eb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c872b3ff934cb40e9a76faedea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10c65e0105f10f0cb44c8dfedd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71b32a770a5be1248e5ffbc113"`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "connectionTested" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "configured" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "environment" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_esocial_config" ALTER COLUMN "enabled" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_risk_status_enum_old" AS ENUM('ativo', 'inativo')`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ALTER COLUMN "status" TYPE "public"."nr1_risk_status_enum_old" USING "status"::"text"::"public"."nr1_risk_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ALTER COLUMN "status" SET DEFAULT 'ativo'`);
        await queryRunner.query(`DROP TYPE "public"."nr1_risk_records_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_risk_status_enum_old" RENAME TO "nr1_risk_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."nr1_risk_level_enum_old" AS ENUM('a', 'b', 'm', 'ma')`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_records" ALTER COLUMN "classificacao_risco" TYPE "public"."nr1_risk_level_enum_old" USING "classificacao_risco"::"text"::"public"."nr1_risk_level_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."nr1_risk_records_classificacao_risco_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."nr1_risk_level_enum_old" RENAME TO "nr1_risk_level_enum"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "icon" text`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "color" text`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_types" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "survey" ALTER COLUMN "groupIds" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "survey" ALTER COLUMN "spaceIds" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "user_entity" ALTER COLUMN "groups" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "distributionChannels" SET DEFAULT ARRAY['app'`);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "adminIds" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "user_group" ALTER COLUMN "conditions" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP CONSTRAINT "PK_8ef8f4acbc766ab04848cf24e43"`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "isNr1"`);
        await queryRunner.query(`ALTER TABLE "gamification_badge" DROP COLUMN "isNr1"`);
        await queryRunner.query(`ALTER TABLE "journeys" DROP COLUMN "isNr1"`);
        await queryRunner.query(`ALTER TABLE "journey_steps" DROP COLUMN "quizConfig"`);
        await queryRunner.query(`ALTER TABLE "news_entity" DROP COLUMN "isNr1"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_space_entity" ADD CONSTRAINT "PK_33acff6f9897bd850d19963eae3" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9d16cbcb2f203b11923ef8dc6"`);
        await queryRunner.query(`DROP TABLE "nr1_trainings"`);
        await queryRunner.query(`DROP TYPE "public"."nr1_trainings_modalidade_enum"`);
        await queryRunner.query(`DROP TYPE "public"."nr1_trainings_tipo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c6b4d9e169fbf70fe0e770a7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b9170a817984af912feb734d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_508f54765fe2a11f2fd52c2008"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_237d44799ea81953bbf8077406"`);
        await queryRunner.query(`DROP TABLE "nr1_action_plans"`);
        await queryRunner.query(`DROP TYPE "public"."nr1_action_plans_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."nr1_action_plans_prioridade_enum"`);
        await queryRunner.query(`ALTER TABLE "nr1_risk_criteria" RENAME COLUMN "version" TO "versao"`);
    }

}
